### ISSUE TITLE
[Documentation] icon can be different from 0x7f02000a

### ISSUE THREAD

**Issue by oroce** [liccowee/Google-Cloud-Messaging--Titanium-#1]
I'm using this module and i was getting ResourceNotFoundException.

And realized in [GCMInentService.java](https://github.com/liccowee/Google-Cloud-Messaging--Titanium-/blob/master/src/com/activate/gcm/GCMIntentService.java#L60) the icon hex code can be different from 0x7f02000a, so everybody should copy from the generated R.java (build/android/gen/com/[company]/[packageName]/R.java) the appropriate one and build their own module via ant.

**Comment by echampet** [comment]
with v0.2 of the plugin it's now configurable via 

``` xml
<property name="com.activate.gcm.icon" type="int">2130837504</property>
```

you've to convert the icon hex code (from R.java) in decimal (type "0x7f020000 to decimal" in google)

**Comment by ankesh27** [comment]
Anyone who can help me with adding custom Icon for Notification ?
 I have an icon Image, now I am lost as what to do..
