### ISSUE TITLE
Notifications not received in Android 4.x if app is closed

### ISSUE THREAD

**Issue by wpjmurray** [liccowee/Google-Cloud-Messaging--Titanium-#14]
I'm using the 0.4 build and got the push notifications working correctly on Android 2.2 and 2.3.3 (I'm using the SDK emulator). The notifications appear correctly even if the app is force quit. Tapping the notification will open the app. So that all works correctly.

In Android 4.x, the notifications appear correclty when the app is running, either in the foreground or background. However, if I force quit the app, the notification does not appear. I see this message in the Titanium console when the message arrives:

[WARN][GTalkService(  227)] [DataMsgMgr] broadcast intent callback: result=CANCELLED forIntent { act=com.google.android.c2dm.intent.RECEIVE cat=[com.packageName.appName](has extras) }

**Comment by wpjmurray** [comment]
On further research, it appears that in Android 3.1+, force-quitting an app puts the app into a "stopped" state and by force-quitting, the user does not want the app running at all, which presumably includes any broadcast receivers, so this seems to be the expected behavior in Android 3.1+. Can anyone confirm this?

**Comment by beaur** [comment]
I'm also seeing this behaviour and wondering the same.

**Comment by wpjmurray** [comment]
I did some additional research after leaving my previous comment and the behavior described is expected and correct: if the user force quits the app, the app should no longer receive notifications.

**Comment by eggman64** [comment]
If anyone else came here looking for answers (like I did) here are some more resources -

http://stackoverflow.com/questions/5775118/android-broadcastreceiver-not-working-after-install/7108611#7108611

https://groups.google.com/forum/#!msg/android-gcm/MqVlA3Sj26c/6O4TdU1pm0UJ
