### ISSUE TITLE
module not found com.activate.gcm

### ISSUE THREAD

**Issue by jaivikram** [liccowee/Google-Cloud-Messaging--Titanium-#16]
I downloaded the 0.4 zip from within the dist folder and dragged it on my project's root. Then I chose the 'copy files' in the dialog box that appears.

On clean and build, the zip was removed and the Titanium studio automatically created a directory called modules in the root of the project.

The project dir structure is like:

Project

```
| - modules
       | - android
                | - com.activate.gcm
                      | - 0.4 (with directories: documentation, example, libs and files gcm.jar, manifest, timodule.xml
| - Resources
      | - app.js (the last lines being: `var push = require('PushNotification'); push.pushNotification();`)
      | - other files...
| - tiapp.xml
    with the section:
   <android xmlns:android="http://schemas.android.com/apk/res/android">
            <manifest package='com.testproject'>
                    <supports-screens android:anyDensity="true"
                        android:largeScreens="true" android:normalScreens="true" android:smallScreens="true"/>
            </manifest>
            <modules>
                <module platform="android" version="0.4">com.activate.gcm</module>
           </modules>
      </android>   
      <property name="com.activate.gcm.sender_id" type="string">MY_SENDER_ID</property>
      <property name="com.activate.gcm.icon" type="int">2130837504</property>
      <property name="com.activate.gcm.component" type="string">com.testproject/com.testproject.HelloWorldActivity</property>
|....rest of the files
```

However, I get this error:

`Uncaught Error: Requested module not found: com.activate.gcm`

From `adb logcat`:

```
D/Module  (31824): Loading module: PushNotification -> Resources/PushNotification.js
E/TiJSError(31824): (main) [1491,1750] ----- Titanium Javascript Runtime Error -----
E/TiJSError(31824): (main) [0,1750] - In ti:/module.js:372,8
E/TiJSError(31824): (main) [0,1750] - Message: Uncaught Error: Requested module not found: com.activate.gcm
E/TiJSError(31824): (main) [0,1750] - Source:   throw new Error("Requested module not found: " + request);
E/V8Exception(31824): Exception occurred at ti:/module.js:372: Uncaught Error: Requested module not found: com.activate.gcm
```

I am using Titanium 2.1.2GA on Ubuntu Linux and testing on a device with Android 2.3.6.

Any help is appreciated.

**Comment by lluisgerard** [comment]
@jaivikram in the `tiapp.xml` file, the `<modules>` tag must not be part of the `<android>` tag. Try to put it just above the module propierties, not adding it to any other tag.

**Comment by jaivikram** [comment]
@lluisgerard  I tried that too, i.e. removed the `<modules>` tag from within `<android>` tag and placed it at the top of tiapp.xml 

```
<?xml version="1.0" encoding="UTF-8"?>
<ti:app xmlns:ti="http://ti.appcelerator.org">
    <modules>
        <module platform="android" version="0.4">com.activate.gcm</module>
    </modules>
. . . . .
```

but the same result.

**Comment by jaivikram** [comment]
@lluisgerard thanks for pitching in. Can you think of any other suggestions? Do you need any other input from me?(like more adb logs, screenshots, etc.)

**Comment by lluisgerard** [comment]
@jaivikram as far as I know, you have it right and, at this point, it should work. 

When you edit the tiapp.xml in Titanium Studio, can you see the module on the Overview window? it must appear there. If not, you should be able to add it.

**Comment by jaivikram** [comment]
@lluisgerard yes it does. Infact it is working correctly both ways. If I add or remove it from tiapp.xml it gets added or removed from the overview->modules list. If I add or remove it from the overview->modules list, the tag gets added or removed from the xml.

maybe I will try it out with a fresh project.

**Comment by jaivikram** [comment]
@lluisgerard  tried with a fresh project, still doesn't work.

**Comment by jaivikram** [comment]
building from source worked.

**Comment by febbyRG** [comment]
hei jaivikram, i have a problem same as it..
can you explain "building from source worked."..
thank you very much..
Any help is appreciated.

**Comment by jaivikram** [comment]
@febbyRG 
If the binary in this git repo doesn't work for you(it's probably due to different build properties paths on different systems, especially on different OS's), follow the "Steps to create module for Titanium use" as mentioned in the readme. It might not work as-is (it didn't for me) and you will need little experience with titanium, java and android to get it thru.

Else you can do this: 
In titanium studio, create-new titanium-module-project.
copy (replace) the src folder from this git repo to your project 
put correct values in the the build properties
install android ndk
try to build the module project
install any other missing dependency if prompted (e.g.: gperf)
if the build is successful - drag&drop the zip file produced in dist folder by the build step above - to your project root in the studio. It shall unzip and use it automatically in the next clean-build.

let me know if you still face issues. (in a bit of hurry right now but can help more later, if required).

lot's of luck. 
Jai

**Comment by febbyRG** [comment]
hi Jai, I'm still have issue, In titanium studio, i've try create-new titanium-module-project with all configuration it's work to build module.
but why the name of modul that I create cannot be set to com.activate.Gcm..
when i try to another name, it's doesn't work (the module cannot be found in mobile app), but when i try to another name and i try to rename code in the all module with the name my package..  
it' work and i get an error : 

[INFO][TiAPI   (  492)] module gcm is => [object Object]
[INFO][TiAPI   (  492)] module gcm is => 
[INFO][TiAPI   (  492)] Registering...
[WARN][C2DMRegistrar(  197)] Invalid parameter sender
[INFO][TiRootActivity(  492)](main) [0,0] checkpoint, on root activity resume. activity = com.pushjaw.googlemessaging.GooglemessagingActivity@40575750
[WARN][ActivityManager(   76)] Launch timeout has expired, giving up wake lock!
[ERROR][C2DMReceiver(  492)](IntentService[GCMIntentService--1]) [402,402] Error: INVALID_PARAMETERS
[ERROR][TiAPI   (  492)] Error during registration : INVALID_PARAMETERS
[INFO][ALERT   (  492)](KrollRuntimeThread) [43,445] Error during registration : INVALID_PARAMETERS
[INFO][ActivityManager(   76)] Displayed com.pushjaw.googlemessaging/.GooglemessagingActivity: +10s212ms

can you help me, what is the parameter that I'm missing?

thank you very much..
Any help is appreciated.

**Comment by miklos-martin** [comment]
@febbyRG: I bet you didn't configure your sender id.
`[WARN][C2DMRegistrar( 197)] Invalid parameter sender`

Follow the steps [here](http://developer.android.com/guide/google/gcm/gs.html) to create a Google API project and retrieve you sender id. Then you should set it in your tiapp.xml.

Cheers

**Comment by chyshu** [comment]
Hi, Everyone

I got a message service_not_avaliable from device.

and run in emulator, I got a error
 Unable to start service Intent { act=com.google.android.c2dm.intent.REGISTER pkg=com.google.android.gsf (has extras) }: not found

module 0.4 + 2.1.4 SDK

anyone have been same problem?

thanks

Roger

**Comment by nigel-ttp** [comment]
Hi Roger,

I wonder if you have the correct version of Android Market installed?  Could you check here http://stackoverflow.com/questions/6840279/android-c2dm-error and let us know if you find out what was missing?
Thanks
