### ISSUE TITLE
How can I set a custom icon?

### ISSUE THREAD

**Issue by beaur** [liccowee/Google-Cloud-Messaging--Titanium-#17]
My app is just taking the main application icon, I'd prefer to use one as per guidelines here: http://developer.android.com/design/style/iconography.html#notification

**Comment by zaherg** [comment]
you should change the value of 

``` xml
<property name="com.activate.gcm.icon" type="int">2130837504</property> <!-- get this from R.java, but converted to decimal, 0x7f020000 give you 2130837504 (type "0x7f020000 to decimal" in google) -->
```

and provide the one you want .. 
am not so sure how you are going to get the value but i think you should read more from R.java

**Comment by ankesh27** [comment]
Anyone who can help me with adding custom Icon for Notification ?
I have an icon Image, now I am lost as what to do..
