### ISSUE TITLE
User clicks the notification vs user opens the app

### ISSUE THREAD

**Issue by lluisgerard** [liccowee/Google-Cloud-Messaging--Titanium-#18]
Rereading this post https://github.com/liccowee/Google-Cloud-Messaging--Titanium-/issues/3 , still don't understand how can I differentiate between these two events:

1) User just opens the app.
2) User opens the app because he/she clicked on the notification.

So, I know I can get the last notification reading the com.activate.gcm.last_data property, but if the app is not running I cannot differentiate between these two events.

Do you have any idea? how do you handle this? I have the app running correctly on iOS but can't get the same behavior in Android because of this.

Thank you very much.

**Comment by Guti** [comment]
Que necesitas? saber si la aplicación estaba abierta o cerrada?

**Comment by lluisgerard** [comment]
@Guti No. Necesito diferenciar si el usuario hace click en la notificación o abre solamente la app.

**Ejemplo con WhatsApp:**

Te llega una notificación de que alguien te ha contestado una conversación:

1) Si abres la app **NO** abre esa conversación., se abre todo como siempre, independientemente de si estaba cerrada o no.

2) Si le das a la notificación **SI** abre esa notificación en concreto. (otra vez, independientemente de si estaba cerrada o no).

Ahora mismo puedo saber la última notificación, pero no puedo saber si el usuario ha hecho click en la notificación o no. Esto lo he conseguido en iPhone porque no se la última notificación, si la app no estaba corriendo en primer plano, se ejecuta el callback.

P.D.: If I find a solution I'll write it in english.

**Comment by Guti** [comment]
OK! te respondo en español, mi ingles no es muy bueno.

Me parece que tendrías que trabajar con esto:

// Para cuando la aplicación esta cerrada en app.js

if(Ti.Platform.name == "android") {
  var activity = Ti.Android.currentActivity;
  var intentData = activity.getIntent().getData();
  if(intentData) {
    // ?
  }
}

// Cuando la app esta en pausa

activity.addEventListener('resume', function(){

});

activity.addEventListener('pause', function(){

});

Y quizás tengas que añadir la notificación en 

https://github.com/liccowee/Google-Cloud-Messaging--Titanium-/blob/master/src/com/activate/gcm/GCMIntentService.java 

antes de launcherintent.addCategory("android.intent.category.LAUNCHER");

algo como  launcherintent.setData(...);

espero que te ayude!

**Comment by lluisgerard** [comment]
@Guti gracias! estoy investigando a partir de lo que me has dicho, de momento no lo he conseguido pero ya lo estoy pillando.

**Comment by Guti** [comment]
En teoría debe de funcionar. Pero veo que quizás también necesitas modificar en la linea 133 de GCMIntentService.java:

mNotificationManager.notify(1, notification);

El numero 1 debe de ser un id que puedas cambiar para que no se sobrescriba la notificación con otra entrante.

Por cierto, tienes que volver generar el modulo gcm una vez modificado. :-)

**Comment by lluisgerard** [comment]
@Guti gracias por la ayuda, pero la verdad es que me estoy llevando un chasco... Pensaba que esto se podría hacer con el módulo de base, sin tener que modificar nada. 
A ver, lo de que solo salga la última notificación tampoco me preocupa, lo que más me interesa es que se abra la ventana que se tiene que abrir.

**Comment by annkiit2** [comment]
I also have the same question...how do you find out whether user has clicked a notification or just started the app...Can you please provide the solution in English...

**Comment by lluisgerard** [comment]
@annkiit2 sorry, I didn't find a way to do it properly.

**Comment by Guti** [comment]
En unos días intento preparar la versión 0.6 con esta nueva función.

**Comment by lluisgerard** [comment]
@Guti en serio? eso sería genial! si necesitas ayuda para probarlo o lo que sea dimelo.

**Comment by lluisgerard** [comment]
@Guti porque, el problema está en que no se puede recibir el activity por su nombre no? es decir, el modulo te crea el .AppNameActivity, cómo se hace para recoger éste activity dentro de Android?

**Comment by lluisgerard** [comment]
Dentro de Appcelerator me refiero

**Comment by lluisgerard** [comment]
@Guti creo que lo tengo. Para hacerlo, me estoy guardando en el intent un putExtra con el json.toString(). Lo que pasa es que estoy teniendo problemas para parsear el JSON luego en Appcelerator.

**Comment by Guti** [comment]
@lluisgerard  Yo también lo tengo. Para obtener el putExtra en titanium es:

  if (Ti.Platform.name == "android") {

```
var activity = Ti.Android.currentActivity;
var intent = activity.getIntent();

if (intent && intent.hasExtra('PushNotifications-Data')) { 

  var data = intent.getStringExtra('PushNotifications-Data');

  if(data) {
    Ti.App.Properties.setString("PushNotifications-Data", data);
    //Ti.App.Properties.setString("com.activate.gcm.last_data", data);
  }
}
```

  }

El problema que tengo y por el motivo que no he subido todavía el código, es cuando la app esta en background. He probado sin éxito:

  win.addEventListener('open', function(e) {

```
if (Ti.Platform.name == "android") {

    var activity = Ti.Android.currentActivity;

    activity.addEventListener('create', function(e) {
      var intent = e.source.getIntent();
      Ti.API.info('create payload:' + intent.getStringExtra('PushNotifications-Data'));
      alert(intent.getStringExtra('PushNotifications-Data'));
    });

    activity.addEventListener('newIntent', function(e) {
      var intent = e.intent;
      Ti.API.info('payload:' + intent.getStringExtra('PushNotifications-Data'));
      alert(intent.getStringExtra('PushNotifications-Data'));
    });

    activity.addEventListener('resume', function(e) {
      var intent = e.intent;

      Ti.API.info('payload:' + intent.getStringExtra('PushNotifications-Data'));
      alert(intent.getStringExtra('PushNotifications-Data'));

    });
  }
```

  });

**Comment by lluisgerard** [comment]
@Guti bueno, en realidad siempre podrías usar el 'resume' general de toda la app. Yo de momento estoy probando en una sola window, por tanto, cada vez que hace el 'open', ejecuto el intent para ver si hay algo. Ya te digo, a mi me está funcionando, el problema lo tengo luego con el JSON.. hago un stringify y tengo muchos "\\\" por en medio. No lo entiendo, porque, un json.toString() debería ser luego parseable a JSON.parse en JavaScript, y eso también me da error.

**Comment by Guti** [comment]
@lluisgerard He subido el código. Yo no tengo ese problema:

https://github.com/Guti/Google-Cloud-Messaging--Titanium-/blob/master/src/com/activate/gcm/GCMIntentService.java

Observa que ademas he añadido: 

int notifyID = 1;
String contentID = (String) data.get("id");

if(contentID != null) {
notifyID = Integer.parseInt(contentID);
}

...

mNotificationManager.notify(notifyID, notification);

https://github.com/Guti/Google-Cloud-Messaging--Titanium-/blob/master/dist/com.activate.gcm-android-0.6.zip

**Comment by lluisgerard** [comment]
@Guti ya he visto qué me pasaba, eran cosas del JSON.parse/stringify anidado, que uno de los anidados era un string entero, y tenía que parsearlo a parte. En fin, que era algo particular mío.

A partir de ahora lo que haré es compilar el mío, ya que por fin he entendido como va esto de los intent/activities. Me gusta cómo haces lo del ID, ahora probaré a ver qué tal :)

**Comment by lluisgerard** [comment]
@Guti ahora lo que me está pasando es que al hacer getExtra, recibo un push anterior, he probado con tu versión y también me pasa. Parece que no se esté actualizando, o que el puntero siempre sea a un sitio anterior :(

**Comment by lluisgerard** [comment]
@Guti Ahora lo estoy probando de la siguiente manera:

GCMIntentService.java:

```
            launcherintent.removeExtra(android.content.Intent.EXTRA_TEXT);
            launcherintent.putExtra(   android.content.Intent.EXTRA_TEXT, "");
            launcherintent.putExtra(   android.content.Intent.EXTRA_TEXT, json.toString());
```

app.js (open de la window):

```
            var currActivity = Titanium.Android.currentActivity;
            var intent       = currActivity.getIntent();
            var passedInText = intent.getStringExtra(Ti.Android.EXTRA_TEXT);

            Ti.API.info('currActivity: ' + JSON.stringify(currActivity));
            Ti.API.info('intent: '       + JSON.stringify(intent));
            Ti.API.info('passedInText: ' + passedInText);

            Ti.API.info("com.activate.gcm.last_data: " + Ti.App.Properties.getString("com.activate.gcm.last_data", ""));
```

Con esto, obtengo información en el `passedInText` solamente cuando el usuario hace click en la notificación. Pero esta información es de pushes anteriores, es decir, la primera vez, veo la info correcta, y a partir de entonces siempre me repite la misma. Luego, si el usuario abre la app, sin pulsar el push, devuelve null.

El que siempre tiene la última info, es el `Ti.App.Properties.getString("com.activate.gcm.last_data", "")` pero no mola porque volvemos al problema de siempre, solo nos quedamos con una notificación (la última).

_Conclusión:_ Si solo muestro el último push en pantalla, esto me soluciona ya mucho camino, pero si quiero mostrar más de uno, no.

**Comment by Guti** [comment]
@lluisgerard Si, estoy haciendo pruebas y getStringExtra siempre obtiene el primer push, es desconcertante.

Creo que seria bueno abrir una nueva conversación en ingles o consultar en el q&a de appcelerator.

**Comment by lluisgerard** [comment]
@Guti voy a abrir una en inglés, a ver si nos aclaramos :)

**Comment by Guti** [comment]
@lluisgerard 

OK! pero como dices anteriormente:

> > A ver, lo de que solo salga la última notificación tampoco me preocupa, lo que más me interesa es que se abra la ventana que se tiene que abrir.

Creo que podrías desarrollar eso en Javascript.

**Comment by lluisgerard** [comment]
@Guti claro, de hecho, con lo del getStringExtra, recibes null o recibes información según si el usuario hace click. Pero al final también necesitaremos varios pushes.

Ahora mismo lo tengo así en el open/resume de la window:

``` JavaScript
// Defino el callback en la misma MainWindow 
// (esto lo hago así pq en toda la aplicación tengo el 
// puntero a MainWindow y puedo ejecutarlo desde cualquier sitio)
MainWindow._pushCallBack = function(params)
{
    // callback
    // params: - data (json)
    //              - clickNotification: (user click?)
};

........

MainWindow.addEventListener('open', function(e){
 // Esto se puede hacer en una línea pero estoy haciendo pruebas
            var currActivity = Titanium.Android.currentActivity;
            var intent       = currActivity.getIntent();
            var passedInText = intent.getStringExtra(Ti.Android.EXTRA_TEXT);

            if (passedInText != null)
            {
                MainWindow._pushCallBack({
                    data:              JSON.parse(Ti.App.Properties.getString("com.activate.gcm.last_data", "")),
                    clickNotification: true
                });             
            };
});
// Luego en el callback:
var gcm = require('com.activate.gcm');
    gcm.registerC2dm
    ( 
        {
            success:function(e)
            {
......
            callback:function(e)
            {
                MainWindow._pushCallBack({
                    data:              e.data,
                    clickNotification: false
                });
....

```

**Comment by Guti** [comment]
@lluisgerard

¿Puedes probar con newIntent?

http://developer.appcelerator.com/question/109551/android-activity-onnewintent

http://developer.appcelerator.com/blog/2011/08/android-intents.html

**Comment by lluisgerard** [comment]
@Guti 
No me devuelve nada, de momento creo que voy a tirar con solo una notificación, pero vamos... hay muchas cosas que se pierden por culpa de tener que usar un módulo y no nativo de JavaScript. Cada vez soy más consciente que para según que cosas es mejor usar nativo.

**Comment by lluisgerard** [comment]
Nativo me refería a escribir las apps directamente en Objective-C i Java, mucho más escalable.

**Comment by fabiomlferreira** [comment]
@lluisgerard 

You can check my version 0.7 of this module. I use the @Guti code but change one thing to correct pass the data from notification to the app.

You can access the data using the following code:
var currActivity = Titanium.Android.currentActivity;
var intent       = currActivity.getIntent();
var passedInText = intent.getStringExtra('PushNotifications-Data');

Version 0.7 - https://github.com/invaderhd/Google-Cloud-Messaging--Titanium-/blob/master/dist/com.activate.gcm-android-0.7.zip

**Comment by lluisgerard** [comment]
@invaderhd thanks for your help. I'm so sorry, I had this thread opened for long time and I just forgot about it.
Right now I'm using this other module that is great, and everything is set in JavaScript, so you don't have to edit any of the Java code because the bridge is already set on the module. https://github.com/iamyellow/gcm.js thanks anyway :)

**Comment by fabiomlferreira** [comment]
I also tried to use that module but when I force close the app the notifications stop to work, so I decide to edit this module and solve my problems.

@lluisgerard check the version 0.2 of your module, I reported the problem and the author fix it ;)
