### ISSUE TITLE
All Working Except for Receipt of Notification

### ISSUE THREAD

**Issue by mlyon** [liccowee/Google-Cloud-Messaging--Titanium-#2]
We currently can only successfully register on a device and so this issue has been really hard to debug.  Shouldn't I be able to put just a simple alert message in the handler for received messages and see something come up to confirm the message made it?  At least as long as the app is running.  I'd like to use the intents as well, but just to make sure something is getting through I was hoping I'd see the alert pop up.

We're successfully registering, successfully passing the registration id to our web server and the web server is getting a success response when it uses the registration id to send a message, but nothing seems to happen on the device.

I'm really not sure how to get more information on where exactly the break down is occurring.  Can we verify the message was sent somehow or if the device actually received it?  I'd be happy to send you test code or communicate by email if you could help me out.

**Comment by liccowee** [comment]
Hi mlyon, I so happy you will successfully registering, successfully passing the registration id to your web server and the web server is getting a success response when you use the registration id to send a message.

First, I have few question want to asking you.
1. Have you use the Google Console API to generate the Project ID(SENDER_ID) and pass as the registration id.
2. If you have success get the Project ID, the another issue is when you build the .apk into device, make sure the app version id must change because the registration id are tight with the project id. If you have change your project id , you must rebuild the app with new version (version 1.0.1), so the device can get new registration.

Hope my answer can help you. Thanks =]

**Comment by mlyon** [comment]
I'll try the number 2 suggestion you have on Monday, but I'm wondering if you can answer one question.  If I have only an alert statement like: alert('got it!') as my function for receiving a notification I should be able to see that without issue right?  For some reason even that test is failing.  I'll try increasing the version number and see if that works for us though.

**Comment by mlyon** [comment]
liccowee,

I tried updating the version number and doing a test.  We are seemingly not getting any push notification.  The server is sending the notification successfully as far as we can tell, but I have only a logging message in my callback function (everything else is commented out).  Looking at the device logs nothing is happening after the push notification is sent.  I don't see anything happening on the device.

Here is my TiApp.xml changes based on yours:

```
<android xmlns:android="http://schemas.android.com/apk/res/android">
        <tool-api-level>14</tool-api-level>
        <manifest android:versionCode="15" android:versionName="1.5" package="com.expertflyer.seatalerts">
            <supports-screens android:anyDensity="true"/>
            <uses-sdk android:minSdkVersion="8"/>
            <permission
                android:name="com.expertflyer.seatalerts.permission.C2D_MESSAGE" android:protectionLevel="signature"/>
            <uses-permission android:name="com.expertflyer.seatalerts.permission.C2D_MESSAGE"/>
            <uses-permission android:name="com.google.android.c2dm.permission.RECEIVE"/>
            <uses-permission android:name="android.permission.WAKE_LOCK"/>
            <uses-permission android:name="android.permission.VIBRATE"/>
            <uses-permission android:name="android.permission.INTERNET"/>
            <uses-permission android:name="android.permission.GET_ACCOUNTS"/>
            <uses-permission android:name="android.permission.USE_CREDENTIALS"/>
            <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
            <application>
                <service android:name="com.activate.gcm.GCMIntentService"/>
                <receiver
                    android:name="com.google.android.gcm.GCMBroadcastReceiver" android:permission="com.google.android.c2dm.permission.SEND">
                    <intent-filter>
                        <action android:name="android.intent.action.BOOT_COMPLETED"/>
                        <category android:name="android.intent.category.HOME"/>
                    </intent-filter>
                    <intent-filter>
                        <action android:name="com.google.android.c2dm.intent.RECEIVE"/>
                        <category android:name="com.expertflyer.seatalerts"/>
                    </intent-filter>
                    <intent-filter>
                        <action android:name="com.google.android.c2dm.intent.REGISTRATION"/>
                        <category android:name="com.expertflyer.seatalerts"/>
                    </intent-filter>
                </receiver>
            </application>
        </manifest>
    </android>
```

Here is my callback:

```
callback:function(e) // called when a push notification is received
            {

                Ti.API.info('Test For Recieve -- Anything In Android Logs?');

            }
```

Is there anything obvious here that you see?  I know that ultimately there will need to be more in the callback function but we are just trying to see if we are even getting a notification.  Thusfar it doesn't seem to work.

**Comment by liccowee** [comment]
Hi mlyon, have you test it on your android device, so far I know the emulator testing may have some issue of push notification. It is encounter you use device to test it out. =]

**Comment by mlyon** [comment]
We are testing on a device.  I noticed you have this included in your tiapp.xml:

```
<modules>
        <module platform="commonjs" version="2.2.0">ti.cloud</module>
    </modules>
```

Is this needed to work properly with gcm?

**Comment by mlyon** [comment]
As an updated we may have resolved this issue.  There are firewall ports that need to be opened in order for the device to receive a notification and that's why we weren't getting the push notification.

From the Google docs:

Note: If your organization has a firewall that restricts the traffic to or from the Internet, you'll need to configure it to allow connectivity with GCM. The ports to open are: 5228, 5229, and 5230. GCM typically only uses 5228, but it sometimes uses 5229 and 5230. GCM doesn't provide specific IPs. It changes IPs frequently. We recommend against using ACLs but if you must use them, take a broad approach such as the method suggested in this support link
