### ISSUE TITLE
Help with tiapp.xml

### ISSUE THREAD

**Issue by chrissadams** [liccowee/Google-Cloud-Messaging--Titanium-#24]
Hi,

I'm struggling to get the module to work.  I've setup all values that I can see in the examples but when our demo app launches it exists without any explanation.

I'm preety sure I'm missing some kind of detail can anyone help?

<?xml version="1.0" encoding="UTF-8"?>
<ti:app xmlns:ti="http://ti.appcelerator.org">
    <id>com.madgex.apps.swordfish</id>
    <name>swordfish</name>
    <version>1.0</version>
    <publisher>chris.adams</publisher>
    <url>http://www.madgex.com</url>
    <description>not specified</description>
    <copyright>2013 by chris.adams</copyright>
    <icon>appicon.png</icon>
    <persistent-wifi>false</persistent-wifi>
    <prerendered-icon>false</prerendered-icon>
    <statusbar-style>default</statusbar-style>
    <statusbar-hidden>false</statusbar-hidden>
    <fullscreen>false</fullscreen>
    <navbar-hidden>false</navbar-hidden>
    <analytics>true</analytics>
    <guid>f9fe3830-5a71-4502-a7a6-45ec5e481ed2</guid>
    <property name="ti.ui.defaultunit" type="string">system</property>
    <iphone>
        <orientations device="iphone">
            <orientation>Ti.UI.PORTRAIT</orientation>
        </orientations>
        <orientations device="ipad">
            <orientation>Ti.UI.PORTRAIT</orientation>
            <orientation>Ti.UI.UPSIDE_PORTRAIT</orientation>
            <orientation>Ti.UI.LANDSCAPE_LEFT</orientation>
            <orientation>Ti.UI.LANDSCAPE_RIGHT</orientation>
        </orientations>
    </iphone>
    <android xmlns:android="http://schemas.android.com/apk/res/android"/>
    <mobileweb>
        <precache/>
        <splash>
            <enabled>true</enabled>
            <inline-css-images>true</inline-css-images>
        </splash>
        <theme>default</theme>
    </mobileweb>
    <modules>
        
    </modules>
    <deployment-targets>
        <target device="iphone">false</target>
        <target device="ipad">false</target>
        <target device="blackberry">false</target>
        <target device="android">true</target>
        <target device="mobileweb">false</target>
    </deployment-targets>
    <sdk-version>3.0.2.GA</sdk-version>
    <property name="com.activate.gcm.sender_id" type="string">620614952700</property> 
    <property name="com.activate.gcm.icon" type="int">2130837504</property> 
    <property name="com.activate.gcm.component" type="string">com.madgex.apps.swordfish/com.madgex.apps.swordfish.GcmActivity</property> 
/ti:app

**Comment by chrissadams** [comment]
I've downloaded the 0.6 version and this isn't crashing but I get the following output:-  [INFO] [2013-03-22 21:55:07,413] com.activate.gcm.js exists: false

Assuming this isn't great.

**Comment by fabiomlferreira** [comment]
@chrissadams  Are you puting the module in the correct folder?
