### ISSUE TITLE
When application is not running , we are not able to get notification

### ISSUE THREAD

**Issue by anisvora** [liccowee/Google-Cloud-Messaging--Titanium-#3]
Hello,

When application is not running , we are not getting any notification.

It can be possible that user restarted phone and registerC2dm callback will not be there , so it will never receive notification.

Also if we put exitOnClose:true in window then application will quite and will not in background .. in that case how to received push notification ?

Regards,
Anis Vora

**Comment by nilkash** [comment]
I am also facing same problem. How to overcome this problem. Need Help....

**Comment by nilkash** [comment]
@licco I checked on console so it's showing me that my device receiving message successfully but not able to display notification because of following error:  W/V8Function(391): Runtime disposed, cannot call function.  Then how to solve this problem. Need Help....... Thank you.......

**Comment by echampet** [comment]
It may help

http://developer.appcelerator.com/question/136149/titanium-v8-runtime-disposed-while-c2dm-receives#answer-239465

**Comment by liccowee** [comment]
The problem have been solved i.e. after closing application receive notification and open application..
Instead of generating notification inside application i.e. inside callback function I generate notification inside module GCMIntentService.java file..

inside GCMIntentService.java change onMessage method in following manner 

```
            HashMap hashdata = new HashMap();

        for (String key : intent.getExtras().keySet()) 
            {
            Log.d(LCAT, "Message key:^^^^^^^^^^^^^^^^^^^^^^ " + key + " value: "
                    + intent.getExtras().getString(key));

            String eventKey = key.startsWith("data.") ? key.substring(5) : key;
            hashdata.put(eventKey, intent.getExtras().getString(key));

        }

        int icon = 0x7f020000;  // AdG: this is my icon from R.java
            CharSequence tickerText = new String("Votodo: " + hashdata.get("messages"));
            long when = System.currentTimeMillis();

        CharSequence contentTitle = "My app name";
        CharSequence contentText = new String(" " + hashdata.get("messages"));

        Intent notificationIntent = new Intent(this, GCMIntentService.class);

        Intent launcherintent = new Intent("android.intent.action.MAIN");
        launcherintent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK | Intent.     FLAG_ACTIVITY_SINGLE_TOP |                  Intent.FLAG_ACTIVITY_CLEAR_TOP);

        launcherintent.setComponent(ComponentName.unflattenFromString("app.packagename/app.packagename.appActivity"));
        launcherintent.addCategory("android.intent.category.LAUNCHER");

        PendingIntent contentIntent = PendingIntent.getActivity(this, 0, launcherintent, 0);

        Notification notification = new Notification(icon, tickerText, when);

        notification.defaults = Notification.DEFAULT_ALL;
        notification.flags = Notification.FLAG_AUTO_CANCEL;
        notification.setLatestEventInfo(context, contentTitle, contentText,contentIntent);
        String ns = Context.NOTIFICATION_SERVICE;
        NotificationManager mNotificationManager = (NotificationManager) getSystemService(ns);
        mNotificationManager.notify(1, notification);
        //C2dmModule.getInstance().sendMessage(data);  .........................  comment this call to callback function in .js file
```

Note: Any one other wants to use this module need rebuild this module change application name, package name , and activity name.

Any problem please let me know.. Thanks =]

**Comment by fastian451** [comment]
sorry for asking such a silly question... I want to know how to rebuild the module??? please tell me specifically for this module..!

**Comment by echampet** [comment]
Please test v0.2 (you can reconfigure without rebuilding).

If you really want to build it, try reading https://github.com/liccowee/Google-Cloud-Messaging--Titanium-/blob/master/README.md, and do step 1-2-5-7-8. On mac you can install ant with http://mxcl.github.com/homebrew/.

Give more detail ...

**Comment by fastian451** [comment]
what is v0.2??? is it the module version????

**Comment by echampet** [comment]
yes it is (https://github.com/liccowee/Google-Cloud-Messaging--Titanium-/tree/master/dist)

**Comment by fastian451** [comment]
thanks for ur help...

cheers..!

**Comment by fastian451** [comment]
one thing more, does this new version gonna solve the issue mentioned in this thread...! and do we have to write a callback function in our app,js?????

**Comment by echampet** [comment]
The new behavior is:
0) you register as usual, send the registration id to your server ....
1) you send a "push" to google with

``` json
{ "data": {
    "ticker": "ticker",
    "title": "title",
    "message": "message",
    "custom": "test"
  },
  "registration_ids": ["a"]
}
```

If you omit "ticker" there will be no ticker ...

2) the phone receive the "push" and create a notification with "ticker","title" and "message" and the icon that you have set with `<property name="com.activate.gcm.icon" type="int">2130837504</property>`
3) it convert the "push" content into json and store it into Ti.App.Properties with key "com.activate.gcm.last_data"
(it store only the last push value)

3) it call the callback function : if the app is started it will succeed (and you can do what you want), else it will fail

4) when you click on the notification, it will start/get app to the front (assuming you've configure `<property name="com.activate.gcm.component" type="string">gcm.gcm/gcm.gcm.GcmActivity</property>`). at this moment you can check if com.activate.gcm.last_data exists and make what you want with it
dont forget to empty it (removeProperties)

**Comment by fastian451** [comment]
previously I had my sender Id in pushNotification.js... Now you haven't mentioned it in your pushNotification.js.. where to mention the sender ID????

**Comment by echampet** [comment]
`<property name="com.activate.gcm.sender_id" type="string">00000000</property> <!-- put your sender_id here -->`

it's in tiapp.xml, in the example directory https://github.com/liccowee/Google-Cloud-Messaging--Titanium-/blob/master/example/tiapp.xml

**Comment by fastian451** [comment]
Thanks  echampet for your time and help.. I have successfully sent the push notification from my php server to my android device... 

cheers....!

**Comment by anisvora** [comment]
Now with V3 we are getting push notification working if application is not in active mode .. but it is not able to start our application when we click on that notification..  it is some thing related to 
<property name="com.activate.gcm.component" type="string">gcm.gcm/gcm.gcm.GcmActivity</property>

what should be there .. com.ait.deal/com.ait.deal.GcmActivity or anything else ?

Regards,
Anis Vora

**Comment by echampet** [comment]
look inside AndroidManifest.xml, in the build dir

you will have something like that

``` xml
<activity android:configChanges="keyboardHidden|orientation|screenSize" android:label="Lyon Capitale" android:name=".GcmActivity" android:theme="@style/Theme.Titanium">
    <intent-filter>
        <action android:name="android.intent.action.MAIN"/>
        <category android:name="android.intent.category.LAUNCHER"/>
    </intent-filter>
</activity>
```

instead of com.ait.deal/com.ait.deal.GcmActivity -> com.ait.deal/com.ait.deal."android:name"

**Comment by lluisgerard** [comment]
@echampet said:

> 4) when you click on the notification, it will start/get app to the front (assuming you've configure <property name="com.activate.gcm.component" type="string">gcm.gcm/gcm.gcm.GcmActivity</property>). at this moment you can check if com.activate.gcm.last_data exists and make what you want with it
> dont forget to empty it (removeProperties)

But, this is not entirely true... I mean, of course the app is opening when you click on the notification, but you have no clue whether the user clicked on it, or just opened the app... Or do you? am i missing something here? do I have to modify the java code for it to work the way I'm talking about?

Thank you,

Lluis
