### ISSUE TITLE
Control sound & vibrate

### ISSUE THREAD

**Issue by Guti** [liccowee/Google-Cloud-Messaging--Titanium-#6]
I need to control the vibration and sound of notification, like Appcelerator ti.cloudpush

But I am a beginner in java.

Something like this?

After -> Notification notification = new Notification(icon, tickerText, when);

<pre>

CharSequence vibrate = (CharSequence) data.get("vibrate");
CharSequence sound = (CharSequence) data.get("sound");

String[] packagename = systProp.getString("com.activate.gcm.component", "").split("/");

if(sound == 'default' && vibrate){
    notification.defaults = Notification.DEFAULT_ALL;
} 
else if(sound == 'default'){
    notification.defaults = Notification.DEFAULT_SOUND;
} 
else if(sound && vibrate){
    // From sound/custom.wav ???
    // notification.sound = file:///android_asset/Resources/sound/"+sound
    notification.sound = Uri.parse("android.resource://"+ packagename[0] +"/assets/Resources/sound/"+sound));
    notification.defaults = Notification.DEFAULT_VIBRATE;
} 
else if(sound){
    notification.sound = Uri.parse("android.resource://"+ packagename[0] +"/assets/Resources/sound/"+sound));
} 
else if(vibrate) {
    notification.defaults = Notification.DEFAULT_VIBRATE; // Notification.DEFAULT_LIGHTS;
}

**Comment by webernir** [comment]
Any news about this one?
How can i add a custom sound (or any sound) to my push notifications?

10x!

**Comment by Guti** [comment]
a little better. but the custom sound does not work

import android.net.Uri;

<pre>
// Custom
CharSequence vibrate = (CharSequence) data.get("vibrate");
CharSequence sound = (CharSequence) data.get("sound");
if("default".equals(sound) && vibrate != null) {
    notification.defaults = Notification.DEFAULT_ALL;
}
else if("default".equals(sound)) {
    notification.defaults = Notification.DEFAULT_SOUND;
}
else if(sound != null && vibrate != null){
    notification.sound = Uri.parse("file:///android_asset/Resources/sound/"+sound);
    notification.defaults = Notification.DEFAULT_VIBRATE;
}
else if(sound != null){
    notification.sound = Uri.parse("file:///android_asset/Resources/sound/"+sound);
}
else if(vibrate != null) {
    notification.defaults = Notification.DEFAULT_VIBRATE;
}
else {
    notification.defaults = Notification.DEFAULT_LIGHTS;
}
//notification.defaults = Notification.DEFAULT_ALL;
</pre>

**Comment by Guti** [comment]
I can now control the sound and vibration:

https://github.com/Guti/Google-Cloud-Messaging--Titanium-

**Comment by appinger** [comment]
can you please compile the module? 

(see: https://github.com/liccowee/Google-Cloud-Messaging--Titanium-/issues/21)

**Comment by Guti** [comment]
https://github.com/Guti/Google-Cloud-Messaging--Titanium-/blob/master/dist/com.activate.gcm-android-0.5.zip
