### ISSUE TITLE
Callback is fired when app opened, but when app closed it asks for application restart

### ISSUE THREAD

**Issue by RodrigoAyala** [liccowee/Google-Cloud-Messaging--Titanium-#8]
Hello guys,

I need some help with a issue:

The app receives the notification without problems on the notification bar when the app is closed, and when the app is previously opened the callback is fired.

The problem is that when the app is closed, and when I click the notification, android try to open the app and shows this dialog: "Restart required - An application restart is required".

What i'm doing wrong?

My Tiapp.xml:

``` javascript
<property name="com.activate.gcm.sender_id" type="string">16068632XXXX</property>
<property name="com.activate.gcm.icon" type="int">2130837504</property>
<property name="com.activate.gcm.component" type="string">cl.continuum.tramites/.PushtestTiActivity</property>
```

and the callback function inside app.js:

``` javascript
callback:function(e) // called when a push notification is received
                {
                    Ti.API.info('JS message event: ' + JSON.stringify(e.data));
                    alert('JS message event: ' + JSON.stringify(e.data));
                                }
```

Thanks for the help!

**Comment by kabeer-anubavam** [comment]
I am getting the same issue Bro but, for me callback: function is not called when the app is in closed state so cant able to list them ...
Please do the needfull.

**Comment by miklos-martin** [comment]
Hello!

I don't know, if you've already found a better solution, but I found a workaround for this a few months ago, when I faced it too. It's not related to this module at all.
https://jira.appcelerator.org/browse/TIMOB-4941

You should place this in your tiapp.xml:

``` xml
    <property name="ti.android.bug2373.disableDetection" type="bool">true</property>
    <property name="ti.android.bug2373.restartDelay" type="int">500</property>
    <property name="ti.android.bug2373.finishDelay" type="int">0</property>
    <property name="ti.android.bug2373.skipAlert" type="bool">true</property>
    <property name="ti.android.bug2373.message"/>
```

Actually it doesn't solve the problem, but **does** make the prompt disappear doing the restart quietly.
Hope it helps.

Cheers
